---
  - name: Install dependencies
    become: True
    apt:
      state: present
      update_cache: yes
      cache_valid_time: 1800
      name:
        - dnsutils
        - dehydrated

  - name: Create delegation script
    become: True
    when: ledns_provide_remote
    template:
      src: upddns.sh.j2
      dest: /etc/dehydrated/upddns.sh
      owner: root
      group: root
      mode: 0750

  - name: Upload hook and configuration
    become: True
    template:
      src: "{{ item.name }}.j2"
      dest: "/etc/dehydrated/{{ item.name }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - name: dnshook.sh
        mode: '0750'
      - name: domains.txt
        mode: '0640'
      - name: config
        mode: '0640'

  - name: Upload le-dns service and timer
    become: True
    template:
      src: "{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    notify: reload
    with_items:
      - dehydrated.service
      - dehydrated.timer
