---
  - name: reload
    become: True
    service:
      name: le-dns.timer
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: restart timer
    become: True
    service:
      name: le-dns.timer
      state: restarted
      enabled: yes
